//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sixagen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendas
    {
        public int ID { get; set; }
        public string Motivo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Empleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
        public string Herramientas_Necesarias { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
