//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sixagen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos_Reparacion
    {
        public int ID { get; set; }
        public string Nombre_Equipo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Dueno { get; set; }
        public Nullable<int> Empleado { get; set; }
        public string Problema { get; set; }
        public byte[] Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Entrada { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
