//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sixagen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int ID { get; set; }
        public int Producto { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio_total { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Empleado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
